### ISSUE TITLE
Difference between the cp and copy file

### ISSUE THREAD

**Issue by tiazahmd** [posborne/linux-programming-interface-exercises#12]
Hi there,
I'm learning from TLPI at the moment and in chapter 4. I was doing the `cp` exercise and I'm somewhat stuck. I saw your solution and implement it. However, the output isn't any different from the actual `copy.c` fiile. In both cases, the files are copying the holes. Also, in your code, you have the following line as well: `while ((numRead = read(inputFd, buf, BUF_SIZE)) > 0)`, which says that the loop will continue unless there is an `EOF` - similar to the actual `copy.c` file as well. Can you tell me how your version of  `cp.c` is any different from `copy.c` given that it is giving me identical output? The file I'm referring to is [this one](https://github.com/posborne/linux-programming-interface-exercises/blob/master/04-file-io-universal-io-model/cpholes.c).
Thanks.

**Comment by posborne** [comment]
Functionally the files generated will be the same, but one is actually taking up less space on disk (for some filesystems) as the file is sparse.  You can see these differences with the `ls -s` option.

I don't have the book in front of me right at the moment and I wrote this awhile ago so maybe I am misunderstanding your question (I don't have copy.c in front of me).

**Comment by tiazahmd** [comment]
Ah, I get it now. You understood my question quite right. I guess I was also trying to find a way how I can distinguish output from the two different sources - file size makes perfect sense. What I was trying to do was do everything as it is until `numread == 0`, then do some additional stuff for the `null` bytes until it hit regular bytes again. Thanks for the clarification, I will mark the issue closed.

**Comment by vtronko** [comment]
This is wrong. It just cuts null bytes, you can check with `du --apparent-size` and also compare sha1sum's.
Dest file just doesn't contain null bytes at all, implementation is wrong.

**Comment by vtronko** [comment]
More specifically, with
```
$ echo 42 > src && dd if=/dev/zero of=src bs=1 count=0 seek=512M
```
this doesn't work:
```
$ ./a.out src dest
$ du --apparent-size dest
1 dest
```
but:
```
$ echo 42 >> src
$ ./a.out src dest
$ du --apparent-size dest
524289	dest
$ du dest
8 dest
```
